
CREATE TABLE IF NOT EXISTS APPS (
name TEXT,
adddate DATE,
PRIMARY KEY(name)
);

CREATE TABLE IF NOT EXISTS GROUPS (
name TEXT,
adddate DATE,
PRIMARY KEY(name)
);

CREATE TABLE IF NOT EXISTS GROUP_APPS (
app TEXT,
groupName TEXT,
adddate DATE,
PRIMARY KEY(app, groupName),
FOREIGN KEY(app) REFERENCES APPS(name),
FOREIGN KEY(groupName) REFERENCES GROUPS(name)
);

CREATE TABLE IF NOT EXISTS RECENT_APPS (
name TEXT,
count INT,
adddate DATE,
PRIMARY KEY(name)
);

COMMIT;
