#!/bin/bash

set -x

cask

# To logout we will check if cask is running and if not kill the user session.

USERNAME=`echo $USER`

if pgrep -f cask >/dev/null

then
  echo "Cask is running"
else
  pkill -KILL -u $USERNAME
fi
